backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - label: "Translations"
    name: "translations"
    folder: "src/data/index"
    extension: "json"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Brand", name: "brand", widget: "string"}
      - {
            label: "Benefits",
            name: "benefits",
            widget: "list",
            fields:
              [
                {
                  label: "Heading", name: "heading", widget: "string"
                },
                {
                  label: "SubHeading", name: "subheading", widget: "string"
                },
                {
                  label: "Text", name: "text", widget: "text"
                }
              ]
            }
