backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - label: "Inhalt Locale"
    name: "inhalt"
    folder: "src/data/index"
    extension: "json"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index"}
      - {label: "Title", name: "title", widget: "string"}
      - {
        label: "Inhalt der Indexseite",
        name: "content",
        widget: "object",
        fields:
          [
            {label: "page header", name: "page header", widget: "string"},
            {label: "page header description", name: "page header description", widget: "string"},
            {label: "specification description", name: "specification description", widget: "string"},
            {label: "price descripgition", name: "price description", widget: "string"},
            {label: "conditions text", name: "conditions text", widget: "markdown"},
            {label: "included in price", name: "included in price", widget: "markdown"},
          ]
      }
      - {
        label: "Allgemeine Bezeichnungen",
        name: "generic",
        widget: "object",
        fields:
          [
            {
              label: "Navbar",
              name: "navbar",
              widget: "object",
              fields:
                [
                  {label: "Support", name: "Support", widget: "string"},
                  {label: "Login", name: "Login", widget: "string"},
                ]
            },
            {label: "powered by", name: "powered by", widget: "string"},
            {label: "Benefits", name: "Benefits", widget: "string"},
            {label: "So funktioniert's", name: "So funktioniert's", widget: "string"},
            {label: "Preise", name: "Preise", widget: "string"},
            {label: "Kontakt", name: "Kontakt", widget: "string"},
            {label: "Demozugang", name: "Demozugang", widget: "string"},
            {label: "Registrieren", name: "Registrieren", widget: "string"},
            {label: "Zufriedene Kunden", name: "Zufriedene Kunden", widget: "string"},
            {label: "Im Preis inbegriffen sind:", name: "Im Preis inbegriffen sind:", widget: "string"},
            {label: "Noch Fragen ?", name: "Noch Fragen ?", widget: "string"},
            {label: "Ihr persönlicher Kontakt", name: "Ihr persönlicher Kontakt", widget: "string"},
            {label: "Besuchen Sie uns auf Twitter", name: "Besuchen Sie uns auf Twitter", widget: "string"},
            {
              label: "Footer",
              name: "footer",
              widget: "object",
              fields:
                [
                  {label: "Impressum", name: "Impressum", widget: "string"},
                  {label: "Der", name: "Der", widget: "string"},
                  {label: "wird unterstützt durch", name: "wird unterstützt durch", widget: "string"}
                ]
            }
          ]
      }
  - label: "Benefits Locales"
    name: "benefits"
    folder: "src/data/benefits"
    extension: "json"
    create: true
    fields:
      - {label: "Sprache", name: "title", widget: "string"}
      - {
        label: "Benefits",
        name: "benefits",
        widget: "list",
        fields:
          [
          {
            label: "Überschrift", name: "heading", widget: "markdown"
          },
          {
            label: "Text", name: "text", widget: "text"
          }
          ]
      }
  - label: "Feature Locales"
    name: "features"
    folder: "src/data/features"
    extension: "json"
    create: true
    fields:
      - {label: "Sprache", name: "title", widget: "string"}
      - {
        label: "Features",
        name: "features",
        widget: "list",
        fields:
          [
          {
            label: "Überschrift", name: "heading", widget: "markdown"
          },
          {
            label: "Text", name: "text", widget: "text"
          }
          ]
        }